name             'mining'
maintainer       '@motoma'
maintainer_email 'motoma@gmail.com'
license          'All rights reserved'
description      'Installs/Configures mining'
long_description 'Yawn'
version          '0.1.1'
